### ISSUE TITLE
More docs?

### ISSUE THREAD

**Issue by Petah** [dmaevsky/rd-parse#1]
Hi,

Is there any more docs on this? I am trying to make a parser for a basic boolean logic such as:

```
key1 == value2 && (key2 == value2 || key3 == value3)
```

but I can't quite figure it out.

**Comment by dmaevsky** [comment]
Sorry for the late reply.
Looks like I need some time to wrap my head around it again myself :) it's been quite some time I didn't use it.
If you are not familiar with EBNF grammar specification and recursive descent parsers in general, you could start there, and a lot of things will become self-explanatory.
If that is not enough, I'll try to find some spare cycles to write smth down.
In your case though, wouldn't a simple eval do the trick?

**Comment by Petah** [comment]
Thanks for the reply. 

Yea my use case was for doing running it through eval, but it comes from user input so I wanted to validate it first. 

I ended up using https://github.com/soney/jsep
