### ISSUE TITLE
Simple example using Y combinator?

### ISSUE THREAD

**Issue by rapodaca** [dmaevsky/rd-parse#5]
I'd like to implement a grammar that I think requires recursion.

The input "a(b(c)d)e" should produce:

```javascript
 [
  [
    "a"
  ],
  [
    "(",
    [
      [
        "b"
      ],
      [
        "(",
        [
          [
            "c"
          ]
        ],
        ")"
      ],
      [
        "d"
      ]
    ],
    ")"
  ],
  [
    "e"
  ]
]
```

My grammar so far is:

```javascript
const grammar = function (token, all, any, plus, optional, node) {
  let open = token(/(\()/g, 'open');
  let close = token(/(\))/g, 'close');
  let letter = token(/([a-z])/g, 'letter');
  
  let run = Y(function (thisRun) {
    return node(any(plus(letter), all(open, thisRun, close)), reduceRun);
  });
  let line = node(plus(run), reduceLine)

  return line;
};

const Y = function (gen) {
  return (function(f) {return f(f)})( function(f) {
    return gen(function() {return f(f).apply(null, arguments)});
  });
};

const reduceRun = (run) => {
  return run.map((u) => {
    return u;
  });
};

const reduceLine = (line) => {
  return line;
};

module.exports = grammar;
```

I use the grammar like this:

```javascript
const Parser = require('rd-parse');
const grammar = require('./grammar');

let input = 'a(b(c)d)e';
let p = new Parser(grammar);
let ast = p.parse(input);

console.log(JSON.stringify(ast, null, 2));
```

Instead of the output I'm after, this code fails with the error: "Error: Parsing failed"

How can I fix this problem? Alternatively, are there any examples illustrating how (and why) to use the Y combinator?

The documentation refers to the examples, but I'm not able to see why my code fails from them.

**Comment by rapodaca** [comment]
I noticed this modified grammar does the job:

```javascript
const grammar = function (token, all, any, plus, optional, node) {
  let open = token(/(\()/g, 'open');
  let close = token(/(\))/g, 'close');
  let letter = token(/([a-z])/g, 'letter');
  
  return Y(function (thisGrammar) {
    let run = node(any(plus(letter), all(open, thisGrammar, close)), reduceRun);
    let line = node(plus(run), reduceLine);

    return line;
  });
};

const Y = function (gen) {
  return (function(f) {return f(f)})( function(f) {
    return gen(function() {return f(f).apply(null, arguments)});
  });
};

const reduceRun = (run) => {
  return run.map((u) => {
    return u;
  });
};

const reduceLine = (line) => {
  return line;
};

module.exports = grammar;
```

However, it appears to require recursion over the entire grammar. Is it possible to define recursion over a more limited set of grammar rules as I originally tried?

**Comment by dmaevsky** [comment]
Sorry for the late reply.
I just had a quick look , and it looks like your input does not conform to
the grammar you are defining in the first case.

let run = Y(function (thisRun) {
    return node(any(plus(letter), all(open, thisRun, close)), reduceRun);
  });

Here `run` defines a rule that matches either a sequence of letters or *the
same* rule enclosed in parentheses.
So this will match strings 'a', '(a)', '(ab)', or '(((abc)))', but not
'(b(c)d)'. There is no rule in your grammar to match the latter.

Let me know if I got this right.

Cheers,
Dmitry

**Comment by dmaevsky** [comment]
Glad to hear that it works for you!
