### ISSUE TITLE
ECMA Script (XXXX) Syntax Extensions

### ISSUE THREAD

**Issue by hypersoft** [dmaevsky/rd-parse#6]
Please, DO NOT USE THESE IN ANY CODE, or specify that your scripts require them.

Your scripts WILL NOT RUN in legacy JavaScript environments, and it makes no sense because the syntax extensions are just shortcuts for being a super-lazy (and sloppy) code-writer.

Also note that in LEGACY JavaScript, nearly all RE Symbols must be escaped to be detected as literals. Escape all of them to be safe. I was not able to run the javascript parser example because of the ES6 Lambdas and JSON Extensions. I will never adopt any JavaScript Syntax extensions because the meaning of the WORD syntax is ambiguous if you change the syntax (parser) (IT IS NO LONGER THE SAME SYNTAX, MEANING NO LONGER THE SAME LANGUAGE).

Furthermore, Object.assign and Array.prototype.map are lazy shortcuts (like most javascript extensions these days). Please provide your own implementations (private/internal API poly-fills) for these functionalities.

[Tested with Mozilla SpiderMonkey 1.4.1]

**Comment by hypersoft** [comment]
> Please, DO NOT USE THESE IN ANY CODE, or specify that your scripts require them.
> 
> Your scripts WILL NOT RUN in legacy JavaScript environments, and it makes no sense because the syntax extensions are just shortcuts for being a super-lazy (and sloppy) code-writer.
> 
> Also note that in LEGACY JavaScript, nearly all RE Symbols must be escaped to be detected as literals. Escape all of them to be safe. I was not able to run the javascript parser example because of the ES6 Lambdas and JSON Extensions. I will never adopt any JavaScript Syntax extensions because the meaning of the WORD syntax is ambiguous if you change the syntax (parser) (IT IS NO LONGER THE SAME SYNTAX, MEANING NO LONGER THE SAME LANGUAGE).
> 
> Furthermore, Object.assign and Array.prototype.map are lazy shortcuts (like most javascript extensions these days). Please provide your own implementations (private/internal API poly-fills) for these functionalities.
> 
> [Tested with Mozilla SpiderMonkey 1.4.1]

UNEXPLICIT SYNTAX IS AN OXYMORON!

**Comment by dmaevsky** [comment]
Geez man, nobody's pushing it down your throat.
If you prefer an ES5 compliant version just npm run build it, and it would "magically" appear in the dist folder...

**Comment by hypersoft** [comment]
lol. thanks for the info. unfortunately i don't use those tools.
