### ISSUE TITLE
Why tokenize up front?

### ISSUE THREAD

**Issue by conartist6** [dmaevsky/rd-parse#7]
This seems to seriously limit the syntaxes parser can handle as compared to testing tokens only when the grammar indicates they may be present.

The current way all tokens must be non-ambiguous (and context free), the other way only the potential tokens that may be valid at a particular location need be considered, and they can be considered in the order the grammar suggests, which is a significant improvement over the source ordering situation that seems to exist at present.

**Comment by dmaevsky** [comment]
I agree. Let me see if there's an easy way to implement this...

**Comment by conartist6** [comment]
I've forked the repo and am going to see if I can do it myself. I'm putting some other improvements in there too like converting your es5 to es6, making your tests actually have assertions, and passing the DSL for Grammar definition as an object instead of many arguments.

**Comment by conartist6** [comment]
I plan to incorporate some of the learnings from this article: https://mrale.ph/blog/2016/11/23/making-less-dart-faster.html

**Comment by conartist6** [comment]
I've nearly got line/col numbers working which will allow pretty-printing syntax errors with source context.

**Comment by conartist6** [comment]
I realize now that while you mostly treat data as immutable you actually mutate your stack. In the past this was fine, but with tokenization happening at parse time a regex token match which has already changed the stack may later be rejected. Oops.

**Comment by dmaevsky** [comment]
Conrad,

Thank you so much ! These are indeed the improvements I was planning to
bring into the next major once I could get enough time to spend on this, so
I would be really grateful if you could PR back your changes when you're
happy with them!
Let me know if I can be of any help.

**Comment by conartist6** [comment]
Certainly, my pleasure. I love the basic idea of the thing -- it's no more or less than I need.

**Comment by conartist6** [comment]
Another thing I like about the changes, there's no longer anything impure going on. Token registration was the particular offender. Just so you can see where this is going, here's the new example code:

```js
const Parser = require('rd-parse');

function Grammar({ Node, Any, All, Optional, Plus, Token }) {
  const Whitespace = Token(/\s+/);
  const _ = Optional(Whitespace);
  const SingleQuoteStringCharacter = Token(/([^'])/);
  const DoubleQuoteStringCharacter = Token(/([^"])/);

  const SingleQuoteString = All(`'`, Optional(Plus(SingleQuoteStringCharacter)) , `'`);
  const DoubleQuoteString = All(`"`, Optional(Plus(DoubleQuoteStringCharacter)) , `"`);

  const String = Node(All(_, Any(SingleQuoteString, DoubleQuoteString), _), (charTokens) => ({
    type: 'StringLiteral',
    value: charTokens.join('')
  }));
})

const p = new Parser(Grammar);

p.parse(`'abc'\n`); // { type: 'StringLiteral', value: `abc` }
p.parse(`":'D"`); // { type: 'StringLiteral', value: `:'D` }
```

**Comment by dmaevsky** [comment]
Oh, Now I do indeed remember why I took the decision to tokenize up-front.
This is exactly the Optional(Whitespace) that was bothering me the most.
Makes complicated grammars a bit too noisy, don't you think?
you have to literally plug it almost everywhere... And if you forget it in
one place, it will come bite you later when you least expect it )

You might have noticed on the Keppel example.
I couldn't find a way to get rid of it without tokenizing upfront.
Do you think there's smth that could be done here ?

**Comment by dmaevsky** [comment]
It's true though that with _ notation it becomes bearable... Might as well
just bite the bullet if that enables much richer grammars...

**Comment by conartist6** [comment]
Yeah I don't think it's really all that bad, considering what you get.

But maybe there are further improvements. What if the rule engine could be applied more than once?

The first pass would be pure tokenization. It would need to understand how to detect strings, comments, etc., which is to say areas that are whitespace-sensitive. It would spit out tokens, which could serve as an input to the second pass of rules, which at this point would no longer need to know about whitespace. This has other benefits I think, such as error messaging. For an error you want to specify what thing was wrong. Having the whole token would allow you to give better error messages too, something like: "unexpected Identifier `foo` at position ...". Otherwise the best you'd be able to do is probably "unexpected character `f` at position ...".

**Comment by dmaevsky** [comment]
Hm,
What you just described seems to be exactly how it is implemented at this
moment:)
The fist pass is the lexer: pure regex based tokenization, and then the
grammar deals with only tokens.
The down side is indeed the fact that the tokenization pass needs to be
context free, which is what I thought you wanted to improve...

**Comment by dmaevsky** [comment]
May I ask you, btw, what is your original use case that necessitated
context dependent tokenization?

**Comment by conartist6** [comment]
Yeah I thought that myself. But tokenization may not be context free. My use case is re-parsing regex source strings. Regex grammar definitely isn't context free. I suspect it's for that reason you've left regex literals out of your es2015 grammar. You'd also have trouble with template strings, wouldn't you?

Even if tokenization could be context free, I wouldn't want to go back to the system where tokenization was expressed as side effects of what is otherwise a pure, functional API.

**Comment by conartist6** [comment]
To simplify, I think it's explicit. You'd be able to opt into the kind of behavior that existed before, yet not required to.

**Comment by conartist6** [comment]
I'm going to try implementing this as mixins: a `LexerMixin` (containing the `Token()` method) and an `TreeMixin` (containing the `Node()` method). Three classes would result:

```js
class Lexer extends LexerMixin(BaseRuleEngine) {}
class TreeBuilder extends TreeMixin(BaseRuleEngine) {}
class Parser extends TreeMixin(LexerMixin(BaseRuleEngine)) {}
```

`Lexer` would turn a string into a token stream.  
`TreeBuilder` would turn a token stream into an AST
`Parser` would turn a string into an AST.

**Comment by dmaevsky** [comment]
So how would the grammar look like finally?
Both context free and context dependent?

You were right : it was indeed cumbersome to include regex literals and
string interpolation into the jsexpr grammar, precisely because of the
context free tokenization.

So I was planning to implement a sort of nesting, where a token in one
grammar can be further broken down using another grammar : that would at
least work for string interpolation.

Is that what you're trying to achieve with those mixins ? I'd like to see
some examples...

**Comment by conartist6** [comment]
Well yes, since you can use all the power of the rule engine either during the lexing stage or the tree generation stage, you'd be able to embed the grammar into itself (with `Y`) in order to handle string interpolation during lexing.

**Comment by conartist6** [comment]
Actually I'm not sure if I'm on the right track here. I'm working on building up a grammar that really exercises this use case. Perhaps some new rule syntax will suffice...

**Comment by conartist6** [comment]
I think a different API is needed for tokenization. My rather messy attempt to use the existing facilities to tokenize template strings shows why:
```js
// template string up until ${ or `
const TemplateStringLiteral = Token(/((?:[^`$\\]|\\.|\$(?!\{))*)/);
```
The regex API just isn't designed for this. You'd much prefer to match lookahead in the affirmative than to try to avoid consuming tokens that match some other pattern. For this reason I think we want something more like a state machine. For each defined state certain characters would be sensitive, meaning they could trigger either token separation or transition to a new state.

**Comment by conartist6** [comment]
I'm sure I've not got everything right yet, but here's what I'm thinking would be a good lexer API.
```js
export const lexer = ({ start, pass, end, consume, matchWith }) => ({
  bare(state, char, ctx) {
    if (char === '`') {
      end();
      consume();
      start();
      return 'string';
    } else if (char === '{') {
      end();
      consume();
      matchWith('}');
    } else if (' \t\r\n'.includes(char)) {
      end();
    } else {
      start();
      pass();
    }
    return state;
  },

  string(state, char, ctx) {
    const { escaped } = ctx;
    ctx.escaped = false;

    if (char === '`') {
      end();
      return 'bare';
    } else if (char === '\\' && !escaped) {
      ctx.escaped = true;
    } else if (char === '$' && peek() === '{' && !escaped) {
      end();
      consume(2);
      matchWith('}');
    } else {
      pass();
    }
    return state;
  },
});
```

**Comment by conartist6** [comment]
Oh yeah, lots still wrong here. I think the biggest problem is that template strings don't properly start an isolated bare context, e.g. you could have something weird like:
```
{ `${}}`
```

To prevent that I'm thinking context gets set up in a closure and we use Y to allow recursion on the outermost definition.

**Comment by conartist6** [comment]
V2:
```
export const lexer = ({ start, get, pass, end, peek, assertMatch, matchWith }) => {
  const consume = (n) => { start(); pass(n); return end(); };
  const ctx = {
    stateStack: [],
    escaped: false,
  };

  return {
    bare(state, char) {
      if (char === '`') {
        end();
        consume();
        start();
        stateStack.push(state);
        return 'templateString';
      } else if (char === '{') {
        end();
        consume();
        matchWith('}');
        return stateStack.pop();
      } else if (char === '}') {
        end();
        assertMatch(consume());
      } else if (' \t\r\n'.includes(char)) {
        end();
      } else if (get()) {
        pass();
      } else {
        start();
      }
      return state;
    },

    templateString(state, char) {
      const { escaped } = ctx;
      ctx.escaped = false;

      if (char === '`') {
        end();
        return 'bare';
      } else if (char === '\\' && !escaped) {
        ctx.escaped = true;
      } else if (char === '$' && peek() === '{' && !escaped) {
        end();
        consume(2);
        matchWith('}');
        stateStack.push(state);
        return 'bare';
      } else {
        pass();
      }
      return state;
    },
  }
};
```

Sorry I keep changing it, I want to make sure the concept is solid before I implement this.

**Comment by conartist6** [comment]
Sorry, moving the example code to a [gist](https://gist.github.com/conartist6/a1b9e644a5934f059a1a1fd5b8848a20) so that I can keep updating it and also you can more clearly see the history of what is changing.

**Comment by dmaevsky** [comment]
Conrad,
The more I was looking at your code, the more I couldn't shake off the feeling that you are trying to throw a baby away with the bathwater :)))

So I finally found some time this weekend to look at it, and here's how I approached the issue:
https://github.com/dmaevsky/rd-parse/tree/v3
I haven't updated the README yet. Basically, I guess, I addressed all of your original concerns:
- The parser is completely stateless now and returning the parsing function directly
- The rules construction toolbox is passed to the Grammar as an object
- I am not tokenizing upfront
- I am still using Regexes for scanning the input stream: I believe it is the most concise and powerful way to implement a string stream scanner without writing pages and pages of code. After all, this is what regexes were designed for! All regexes match from the beginning of input (/^.../), so I am trying them always at the current position to avoid unnecessary forward searches.
- I still kept the way to ignore certain chunks of input such as whitespace and comments, while making it context sensitive
- Overall, there's actually LESS code than there was before :)
- I implemented string interpolation for the ES6 grammar using the new version of the parser: https://github.com/dmaevsky/rd-parse-jsexpr/tree/v1
- I added some tests (I prefer AVA to Jest), and I will definitely add some more tomorrow... I might have missed something. Bug fixes and extra tests would be really appreciated !

Please, let me know what you think, so that I could probably close this issue...

**Comment by conartist6** [comment]
Haha perhaps, perhaps. I like what you've done here. The pure API is a big improvement. I think you'll also want to look into memoization, which will be key to this being an O(n) parser.

I'm having fun with my fork, and will probably try to publish it sooner or later. Feel free to close the issue.

**Comment by dmaevsky** [comment]
Published v3, so closing it now...
