### ISSUE TITLE
None

### ISSUE THREAD

**Issue by conartist6** [dmaevsky/rd-parse#8]
Could there be a `None` production rule? It would simplify implementation of grammars that include epsilon.

**Comment by dmaevsky** [comment]
Could you give me an example of the grammar that you have in mind?
Is it impossible to describe it with the current tools or just "harder" or
"more verbose"?

**Comment by conartist6** [comment]
It's fine, I can just distribute optional. I mostly liked the idea of having my grammar follow the spec as closely as possible.
